### ISSUE TITLE
To-Do List item(Java)

### ISSUE THREAD

**Issue by vaidyamilind** [rodrigorodrigues/microservices-design-patterns#39]
Hey,
I would love to work on this
-       Java - Add Service Discovery(Eureka)
-       Java - Add Zuul(Gateway)
-       Java - Add Maven Docker Plugin 

Is this already completed? because pom.xml already contains the fabric.io plugin should I change to spring-boot build image  plugin

**Comment by rodrigorodrigues** [comment]
Hi @vaidyamilind,

Thanks for your interesting on helping, I've replaced Eureka/Zuul with Consul a few months ago because has better support for non Java apps like Python/Go.

I was trying without luck to upgrade to Spring Native but tests stopping working. If you wanna give a try just pushed code for PR - https://github.com/rodrigorodrigues/microservices-design-patterns/pull/40

Thanks

**Comment by vaidyamilind** [comment]
Hi @rodrigorodrigues,
Little confused what to do. 
We need upgradation to Spring Native for all and with tests all passing?

**Comment by rodrigorodrigues** [comment]
Hi @vaidyamilind ,

Yes, that's right. It seems tests are not working with latest spring boot version with Native support(`mvn spring-boot:build-image`).

Thanks

**Comment by rodrigorodrigues** [comment]
Issue has been fixed in latest commit.
